/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.finops.deep;import cn.zhuatech.finops.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                               */
@RestController @RequestMapping("/api/finops-ops") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                      */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                 */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/accounts")ApiResponse<?> account(@Valid @RequestBody DeepDomainService.AccountRequest r){return ApiResponse.ok(s.account(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/budgets")ApiResponse<?> budget(@Valid @RequestBody DeepDomainService.BudgetRequest r){return ApiResponse.ok(s.budget(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/accounts/{id}/costs")ApiResponse<?> cost(@PathVariable Long id,@Valid @RequestBody DeepDomainService.CostRequest r){return ApiResponse.ok(s.ingest(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/accounts/{id}/recommendations")ApiResponse<?> recommend(@PathVariable Long id,@Valid @RequestBody DeepDomainService.RecommendationRequest r){return ApiResponse.ok(s.recommend(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/recommendations/{id}/realize")ApiResponse<?> realize(@PathVariable Long id,@Valid @RequestBody DeepDomainService.RealizeRequest r){return ApiResponse.ok(s.realize(id,r));}}
