/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.finops.deep;import cn.zhuatech.finops.common.ApiResponse;import org.springframework.web.bind.annotation.*;/**
                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                               */
@RestController @RequestMapping("/api/admin/finops-ops") public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                           */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/accounts/{id}/activate")ApiResponse<?> activate(@PathVariable Long id){return ApiResponse.ok(s.activate(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/recommendations/{id}/approve")ApiResponse<?> approve(@PathVariable Long id){return ApiResponse.ok(s.approve(id));}}
