/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.finops;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DeepFinopsOpsTests{@Autowired MockMvc mvc;
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void budgetAnomalyAndOptimizationFormClosedLoop()throws Exception{long a=activeAccount("CLOUD-1");post("/api/finops-ops/budgets","{\"organizationCode\":\"ZH-SH\",\"costCenter\":\"CC-RD\",\"fiscalMonth\":\"2026-09\",\"budgetAmount\":1000,\"warningPercent\":80}");post("/api/finops-ops/accounts/"+a+"/costs",cost("LINE-1",900,500,false)).andExpect(jsonPath("$.data.alertsCreated.length()").value(3));long r=id(post("/api/finops-ops/accounts/"+a+"/recommendations","{\"recommendationNo\":\"OPT-1\",\"resourceId\":\"vm-001\",\"actionType\":\"RIGHTSIZE\",\"estimatedMonthlySavings\":300}").andReturn());admin("/api/admin/finops-ops/recommendations/"+r+"/approve","{}");post("/api/finops-ops/recommendations/"+r+"/realize","{\"actualMonthlySavings\":260,\"note\":\"降配后运行稳定\"}").andExpect(jsonPath("$.data.status").value("REALIZED"));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void inactiveAccountAndDuplicateBillAreBlocked()throws Exception{long a=account("CLOUD-2");post("/api/finops-ops/accounts/"+a+"/costs",cost("LINE-X",100,100,true)).andExpect(status().isConflict());admin("/api/admin/finops-ops/accounts/"+a+"/activate","{}");post("/api/finops-ops/accounts/"+a+"/costs",cost("LINE-2",100,100,true));post("/api/finops-ops/accounts/"+a+"/costs",cost("LINE-2",100,100,true)).andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void recommendationRequiresApprovalAndBudgetPercentIsValidated()throws Exception{long a=activeAccount("CLOUD-3");long r=id(post("/api/finops-ops/accounts/"+a+"/recommendations","{\"recommendationNo\":\"OPT-3\",\"resourceId\":\"disk-3\",\"actionType\":\"DELETE_IDLE\",\"estimatedMonthlySavings\":100}").andReturn());post("/api/finops-ops/recommendations/"+r+"/realize","{\"actualMonthlySavings\":90,\"note\":\"删除\"}").andExpect(status().isConflict());post("/api/finops-ops/budgets","{\"organizationCode\":\"ZH-SH\",\"costCenter\":\"CC-X\",\"fiscalMonth\":\"2026-09\",\"budgetAmount\":1000,\"warningPercent\":120}").andExpect(status().isBadRequest());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 long account(String n)throws Exception{return id(post("/api/finops-ops/accounts","{\"organizationCode\":\"ZH-SH\",\"accountCode\":\""+n+"\",\"provider\":\"CLOUD_PROVIDER\",\"name\":\"生产云账号\"}").andReturn());}/**
                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                  */
long activeAccount(String n)throws Exception{long a=account(n);admin("/api/admin/finops-ops/accounts/"+a+"/activate","{}");return a;}/**
                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                       */
String cost(String n,double amount,double baseline,boolean tagged){return "{\"providerLineId\":\""+n+"\",\"serviceCode\":\"COMPUTE\",\"resourceId\":\"vm-001\",\"costCenter\":\"CC-RD\",\"amount\":"+amount+",\"baselineAmount\":"+baseline+",\"tagged\":"+tagged+",\"usageDate\":\"2026-09-01\"}";}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
ResultActions post(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
ResultActions admin(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
long id(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}}
